// <auto-generated />
namespace WeatherProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202110252039055_new-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
